spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: validate
    datasource:
        platform: postgres
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/db_desafio_softplan
        driver-class-name: org.postgresql.Driver
        hikari:
          auto-commit: true
    flyway:
      clean-disabled: false
      clean-on-validation-error: false
      table: migrations_history
      locations:
        - classpath:db/migrations

jwt:
    secret: 463a6dcdce9b50b5a803449692b5523c
    expiration: 86400000