spring:
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
    datasource:
        platform: postgres
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/db_desafio_softplan
        driver-class-name: org.postgresql.Driver

jwt:
    secret: 463a6dcdce9b50b5a803449692b5523c
    expiration: 86400000 # 1 dia